name: Android CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v4

      # - name: Grant execute permission for gradlew
      #   working-directory: ./android
      #   run: chmod +x gradlew

      # - name: Build with Gradle
      #   working-directory: ./android
      #   run: ./gradlew build

      # - name: Upload dev APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-dev
      #     path: apk/app-debug.apk

      - name: Upload dev APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev
          path: apk/app-debug.apk
